name: ros
services:
  ros2:
    image: osrf/ros:humble-desktop-full
    container_name: ros-ros2
    environment:
        DISPLAY: host.docker.internal:0.0
    ports:
        - "10000:10000"  
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
